# Publishes to the Bazel Central Registry. See .bcr/README.md.
name: Publish to the Bazel Central Registry

on:
  # Run from release.yml.
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
    secrets:
      publish_token:
        required: true

  # In case of problems, enable manual dispatch from the GitHub UI.
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string

jobs:
  publish-to-bcr:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v0.0.1
    with:
      tag_name: ${{ inputs.tag_name }}
      # bazelbuild/bazel-central-registry fork used to open a pull request.
      registry_fork: simuons/bazel-central-registry
    permissions:
      attestations: write
      contents: write
      id-token: write
    secrets:
      # Necessary to push to the BCR fork and open a pull request.
      publish_token: ${{ secrets.publish_token }}
