# Cut a release whenever a new tag is pushed to the repo.
# You should use an annotated tag, like `git tag -a v1.2.3`.
name: Release

on:
  push:
    tags:
      - 'v*.*.*'

  # In case of problems, enable manual dispatch from the GitHub UI.
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string

# Uses the `release_ruleset` workflow to generate provenance attestation files
# referenced by the `publish-to-bcr` workflow.
#
# Based on .github/workflows/release.yml from aspect-build/rules_lint v1.3.5.
# See .bcr/README.md.

permissions:
  attestations: write # Needed to attest provenance
  contents: write # Needed to create release
  id-token: write # Needed to attest provenance

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7.2.2
    with:
      bazel_test_command: "bazel test //src/... //test/... //third_party/..."
      prerelease: false
      release_files: rules_scala-*.tar.gz
      tag_name: ${{ inputs.tag_name || github.ref_name }}

  publish-to-bcr:
    needs: release
    uses: ./.github/workflows/publish-to-bcr.yml
    with:
      tag_name: ${{ inputs.tag_name || github.ref_name }}
    secrets:
      bcr_publish_token: ${{ secrets.bcr_publish_token }}
